### ISSUE TITLE
none of the mapbox default styles render correctly

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/node-mapbox-gl-native#123] opened 2015-05-18 16:07 UTC
They are only showing the terrain layer and a background, nothing else: 
![screen shot 2015-05-18 at 12 06 30 pm](https://cloud.githubusercontent.com/assets/108094/7684730/63ec80b8-fd56-11e4-9a97-071b10072d32.png)

**Comment by mikemorris** [comment] 2015-05-18 16:12
Possible this is caused by updated styles running against an older tag of mapbox-gl-native? I'm trying to wait for https://github.com/mapbox/mapbox-gl-native/issues/1565 to be fixed before tagging a new version, can you test these styles against `master` though?

**Comment by mikemorris** [comment] 2015-05-18 21:10
This appears to be fixed in `HEAD` which is using a newer release of mbgl, just hasn't been tagged/published yet.

![0](https://cloud.githubusercontent.com/assets/1149913/7690307/c1a2457e-fd80-11e4-8ca5-dc83bd6e3d3f.png)

**Comment by samanpwbb** [comment] 2015-06-15 16:08
Re-opening until this is fixed in node-mbgl. App team needs to be able to track the status of this issue.

**Comment by mikemorris** [comment] 2015-06-15 16:48
This refs some of the concerns in https://github.com/mapbox/mapbox-gl-native/pull/1289

**Comment by bsudekum** [comment] 2015-06-23 19:26
@mikemorris I think we're good here?

**Comment by samanpwbb** [comment] 2015-06-23 20:10
:clap:

**Closed** 2015-06-23 20:10 UTC
Labels: bug
