### ISSUE TITLE
when data isn't available from vector tile, error message is "invalid date"

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/node-mapbox-gl-native#102] opened 2015-03-18 00:09 UTC
why invalid date? Do you know @mikemorris ? Is this supposed to be invalid data?

**Comment by mikemorris** [comment] 2015-03-18 15:37
Um, that seems odd. Write up a test case in a pull request?

**Comment by mikemorris** [comment] 2015-04-08 20:49
This appears to stem from the [example `mbgl.FileSource` implementation](https://github.com/mapbox/node-mapbox-gl-native#implementing-a-file-source) which always expects an `expires` header, even for responses with a status code other than `200`. This is printing `Invalid Date` when `res.headers.expires` does not exist, which is happening for responses with a `400` status code.

```
if (err) {
     req.respond(err);
} else if (res.statusCode == 200) {
    var response = {};

    if (res.headers.modified) { response.modified = new Date(res.headers.modified); }
    if (res.headers.expires) { response.expires = new Date(res.headers.expires); }
    if (res.headers.etag) { response.etag = res.headers.etag; }
    response.data = body;
    req.respond(null, response);
} else {
    console.warn(new Date(res.headers.expires));
}
```

**Comment by mikemorris** [comment] 2015-04-08 21:19
Reproducing this at:
```
latitude: 35.68
longitude: 139.72
zoom: 16
```

I originally thought that this was a bad or missing vector tile, but the actual requests triggering this are for `65280-65533.pbf`, so this is most likely caused by https://github.com/mapbox/mapbox-gl-native/issues/931. Cherry-picking https://github.com/mapbox/mapbox-gl-native/pull/946 into `static-render` branch of mbgl should fix this, but is it reasonable to expect all responses to have an `expires` header regardless of status code?

**Comment by mikemorris** [comment] 2015-04-08 22:01
Should be fixed by https://github.com/mapbox/node-mapbox-gl-native/commit/40d47bc2c6a1815e590c8203a5539b46d811e2a5

**Closed by mikemorris** 2015-04-08 22:01 UTC

**Comment by mikemorris** [comment] 2015-04-08 22:23
https://github.com/mapbox/node-mapbox-gl-native/commit/9363d94c36d082a3c410534b7ce34c77cb63c86d fixes this completely by returning the actual error message from the HTTP response in the example instead of printing a possibly invalid Date.
